### ISSUE TITLE
Implement tasks

### ISSUE THREAD

**Issue by Thynkon** [HEIG-VD-S3-PW/DAI-LAB-04#34]
### Tasks

- [x] list
- [x] add (add needs)
- [x] delete (also handle substasks/dependencies - is required?)
- [x] update (before finishing, are all required tasks done?)
- [x] add subtasks
- [x] delete subtasks
- [x] update subtasks (required or not)
- [x] handle needs
- [x] handle errors (return proper http status)
